// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IdentifyImg: typeof import('./src/components/identify-img/src/IdentifyImg.vue')['default']
    NavHeader: typeof import('./src/components/nav-header/src/NavHeader.vue')['default']
    NavMenu: typeof import('./src/components/nav-menu/src/NavMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubMenu: typeof import('./src/components/nav-menu/src/SubMenu.vue')['default']
    SvgIcon: typeof import('./src/components/svg-icon/src/SvgIcon.vue')['default']
    UserInfo: typeof import('./src/components/nav-header/src/UserInfo.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
  }

}
